# Generated by Django 5.1 on 2024-09-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_value',
            new_name='variation_value',
        ),
    ]
