# Generated by Django 5.1 on 2024-10-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='stauts',
            new_name='status',
        ),
    ]
