# Generated by Django 5.1 on 2024-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_options_productvariationstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariationStock',
        ),
    ]
