# Generated by Django 5.1 on 2024-09-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_variatons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variatons',
            new_name='variations',
        ),
    ]
