# Generated by Django 5.1 on 2024-11-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_remove_cartitem_variations_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
