# Generated by Django 5.1 on 2024-11-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_rename_variation_cartitem_variations'),
        ('store', '0008_variation_stock_delete_productvariationstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
