# Generated by Django 5.1 on 2024-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_created_at_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('success', 'success'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
