# Generated by Django 5.1 on 2024-10-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
